#!/bin/bash
#
# This tool is designed to
# download all required apks
#

if [[ $# != 4 ]]; then
    echo "Usage: $0 <MODEL> <SDK> <ROOT_DIR> <CLEAN_MODE>"
    exit 1
fi

MODEL="$1"
SDK="$2"
ROOT_DIR="$3"
CLEAN_MODE="$4"

SCRIPT_ROOT_DIR=$(realpath $(dirname "$0"))

CAPPS="$ROOT_DIR/capps"
mkdir "$CAPPS" "$CAPPS/preload" "$CAPPS/priv-app" "$CAPPS/perms"

generate_removable_sysconfig() {
    local PACKAGE_PATH="$1"
    
    echo -e "   \e[3;36m[+] Generating removable sysconfig for $(basename "$PACKAGE_PATH")\e[0m"

    local AAPT_RESULT=$(aapt dump badging "$PACKAGE_PATH" 2> /dev/null)

    local PACKAGE_LABEL_NO_SPACES=$(echo "$AAPT_RESULT" | rg -e "application-label:\'([^\']+)\'" -or '$1')
    PACKAGE_LABEL_NO_SPACES="${PACKAGE_LABEL// /}"
    local PACKAGE_NAME=$(echo "$AAPT_RESULT" | rg -e "package: name=\'([^\']+)\'" -or '$1')

    cat << EOF > "$CAPPS/perms/sysconfig_$PACKAGE_LABEL_NO_SPACES.xml"
<?xml version="1.0" encoding="utf-8"?>
<config>
    <!-- Automatically generated by the debloater. Do not edit unless you are sure what you are doing -->
    <removable-system-package package="${PACKAGE_NAME}" />
</config>
EOF
}

download_from_samsungstore() {
    local PACKAGE_LABEL="$1"
    local PACKAGE_NAME="$2"

    local PACKAGE_LABEL_NO_SPACES="${PACKAGE_LABEL// /}"
    local TARGET_DIR="$CAPPS/preload/${PACKAGE_LABEL_NO_SPACES}_preload"
    
    echo -e "\e[3;36m[+] Downloading latest $PACKAGE_LABEL\e[0m"
    
    mkdir "$TARGET_DIR"
    OUT_DIR="$TARGET_DIR" \
        OUT_NAME="$PACKAGE_LABEL_NO_SPACES.apk" \
        bash $SCRIPT_ROOT_DIR/sad.sh \
        -m "$MODEL" \
        -v "$SDK" \
        -p "$PACKAGE_NAME"

    if [[ $? != 0 ]]; then
        echo -e "\e[1;31m[-] Failed to download $PACKAGE_LABEL.apk\e[0m"
        return 1
    fi
}

download_from_github() {
    local REPO="$1"
    local APP_TYPE="$2"       # preload / priv-app
    local APP_NAME="$3"
    local REGEX_MASK="$4"     # mask for link search
    local TARGET_DIR
    
    echo -e "\e[3;36m[+] Downloading latest $APP_NAME\e[0m"
    
    TARGET_DIR="$CAPPS/$APP_TYPE/$APP_NAME"
    if [[ "$APP_TYPE" == "preload" ]]; then
        TARGET_DIR="$CAPPS/$APP_TYPE/${APP_NAME}_preload"
    fi
    
    mkdir -p "$TARGET_DIR"

    local GITHUB_API=$(curl -L -H 'Accept: application/vnd.github+json' "https://api.github.com/repos/$REPO/releases" 2>/dev/null | jq '.[0]')
    
    if [[ $? -ne 0 || -z "$GITHUB_API" || "$GITHUB_API" == 'null' ]]; then
        echo -e "\e[1;31m[-] Failed to get latest release of $APP_NAME\e[0m"
        exit 1
    fi

    local DOWNLOAD_URL=$(echo "$GITHUB_API" | rg -e "\"browser_download_url\": \"($REGEX_MASK)\"" -or '$1')

    if [[ -z "$DOWNLOAD_URL" ]]; then
        echo -e "\e[1;31m[-] Could not find APK matching pattern for $APP_NAME\e[0m"
        exit 1
    fi

    curl -L "$DOWNLOAD_URL" -o "$TARGET_DIR/$APP_NAME.apk"
    
    if [[ $? -ne 0 ]]; then
        echo -e "\e[1;31m[-] Failed to download $APP_NAME.apk\e[0m"
        exit 1
    fi
}

download_from_fdroid() {
    local PACKAGE_LABEL="$1"
    local PACKAGE_NAME="$2"
    
    local PACKAGE_LABEL_NO_SPACES="${PACKAGE_LABEL// /}"
    
    echo -e "\e[3;36m[+] Downloading latest $PACKAGE_LABEL (F-Droid)\e[0m"
    mkdir "$CAPPS/preload/${PACKAGE_LABEL_NO_SPACES}_preload"

    LATEST_PACKAGE_VERSION=$(curl -Ls "https://f-droid.org/api/v1/packages/$PACKAGE_NAME" | jq '.packages[0].versionCode')
    curl -L "https://f-droid.org/repo/${PACKAGE_NAME}_$LATEST_PACKAGE_VERSION.apk" -o "$CAPPS/preload/${PACKAGE_LABEL_NO_SPACES}_preload/Fennec.apk"
    if [[ $? != 0 ]]; then
        echo -e "\e[1;31m[-] Failed to download $PACKAGE_LABEL.apk\e[0m"
        exit 1
    fi
}

# if [[ "$CLEAN_MODE" == 'e' ]]; then
#     echo -e '\e[3;36m[+] Downloading latest microG\e[0m'
#
#     curl -Ls -H 'Accept: application/vnd.github+json' https://api.github.com/repos/microg/GmsCore/releases | jq '.[0]' > "$CAPPS/GmsCore.json"
#     if [[ $? != 0 ]]; then
#         echo -e '\e[1;31m[-] Failed to get latest release\e[0m'
#         exit 1
#     fi
#     
#     mkdir "$CAPPS/priv-app/GmsCore"
#     curl -L $(cat "$CAPPS/GmsCore.json" | rg -e "\"browser_download_url\": \"(https://.*com.google.android.gms-[^-]*-hw\.apk)\"" -or '$1') -o "$CAPPS/priv-app/GmsCore/GmsCore.apk"
#     if [[ $? != 0 ]]; then
#         echo -e '\e[1;31m[-] Failed to download GmsCore.apk\e[0m'
#         exit 1
#     fi
#
#     mkdir "$CAPPS/priv-app/FakeStore"
#     curl -L $(cat "$CAPPS/GmsCore.json" | rg -e "\"browser_download_url\": \"(https://.*com.android.vending-[^-]*-hw\.apk)\"" -or '$1') -o "$CAPPS/priv-app/FakeStore/FakeStore.apk"
#     if [[ $? != 0 ]]; then
#         echo -e '\e[1;31m[-] Failed to download FakeStore.apk\e[0m'
#         exit 1
#     fi
# fi

# echo -e '\e[3;36m[+] Downloading latest F-Droid\e[0m'
# mkdir "$CAPPS/preload/FDroid_preload"
#
# curl -L 'https://f-droid.org/F-Droid.apk' -o "$CAPPS/preload/FDroid_preload/FDroid.apk"
# if [[ $? != 0 ]]; then
#     echo -e '\e[1;31m[-] Failed to download F-Droid.apk\e[0m'
#     exit 1
# fi

download_from_github 'florisboard/florisboard' 'preload' 'FloridBoard' 'https://.*florisboard.*\.apk'
download_from_github 'libre-tube/LibreTube' 'preload' 'LibreTube' 'https://.*app-release\.apk'
download_from_github 'PVOT-OSS/Messages' 'preload' 'Messages' 'https://.*Messages-.*release\.apk'

download_from_fdroid 'Fennec' 'org.mozilla.fennec_fdroid'
download_from_fdroid 'Aurora Store' 'com.aurora.store'

download_from_samsungstore 'VoiceRecorder' 'com.sec.android.app.voicenote'
download_from_samsungstore 'MyFiles' 'com.sec.android.app.myfiles'
download_from_samsungstore 'Clock' 'com.sec.android.app.clockpackage'
download_from_samsungstore 'Calendar' 'com.samsung.android.calendar'
download_from_samsungstore 'Calculator' 'com.sec.android.app.popupcalculator'

echo -e '\e[3;36m[+] Generating XML files\e[0m'

for DIR in "$CAPPS/priv-app"; do
    [[ -d "$DIR" ]] || continue

    while IFS= read -r APK_PATH; do
        APK_NAME=$(basename "$APK_PATH" .apk)
        
        echo -e "   \e[3;36m[*] Generating $APK_NAME XMLs\e[0m"
        bash "$SCRIPT_ROOT_DIR/generate-perm-xml.sh" "$APK_PATH" &> /dev/null
    done < <(find "$DIR" -mindepth 1 -type f -name "*.apk")
done

mv "$PWD/output/"* "$CAPPS/perms" 2> /dev/null
rm -rf "$SCRIPT_ROOT_DIR/data"

sudo chown -R 0:0 "$CAPPS"
